from flask import Flask, render_template, request
import pytz
from datetime import datetime

app = Flask(__name__)

# the list of time zones for the dropdown menu
timezones = [
    "GMT",
    "IBST",
    "WET",
    "Z",
    "EGST",
    "BST",
    "CET",
    "DFT",
    "IST",
    "MET",
    "WAT",
    "WEDT",
    "WEST",
    "CAT",
    "CEDT",
    "CEST",
    "EET",
    "HAEC",
    "IST Israel",
    "MEST",
    "SAST",
    "USZ1",
    "WAST",
    "AST Arabia",
    "EAT",
    "EEDT",
    "EEST",
    "FET",
    "IDT",
    "IOT",
    "MSK",
    "SYOT",
    "IRST",
    "AMT Armenia",
    "AZT",
    "GET",
    "GST Gulf",
    "MUT",
    "RET",
    "SAMT",
    "SCT",
    "VOLT",
    "AFT",
    "IRDT",
    "HMT",
    "MAWT",
    "MVT",
    "ORAT",
    "PKT",
    "TFT",
    "TJT",
    "TMT",
    "UZT",
    "YEKT",
    "IST Indian",
    "SLST",
    "NPT",
    "BDT Bangladesh",
    "BIOT",
    "BST Bangladesh",
    "BTT",
    "KGT",
    "OMST",
    "VOST",
    "CCT",
    "MMT",
    "MST Myanmar",
    "CXT",
    "DAVT",
    "HOVT",
    "ICT",
    "KRAT",
    "THA",
    "WIT",
    "ACT",
    "AWST",
    "BDT",
    "CHOT",
    "CIT",
    "CST China",
    "CT",
    "HKT",
    "IRKT",
    "MST Malaysia",
    "MYT",
    "PST Philippine",
    "SGT",
    "SST",
    "ULAT",
    "WST",
    "CWST",
    "AWDT",
    "EIT",
    "JST",
    "KST",
    "TLT",
    "YAKT",
    "ACST",
    "CST Australia Central",
    "AEST",
    "ChST",
    "CHUT",
    "DDUT",
    "EST Australia",
    "PGT",
    "VLAT",
    "ACDT",
    "CST Australia Central Summer",
    "LHST",
    "AEDT",
    "BST Bougainville",
    "KOST",
    "LHST Lord Howe Summer",
    "MIST",
    "NCT",
    "PONT",
    "SAKT",
    "SBT",
    "SRET",
    "VUT",
    "NFT",
    "FJT",
    "GILT",
    "MAGT",
    "MHT",
    "NZST",
    "PETT",
    "TVT",
    "WAKT",
    "CHAST",
    "NZDT",
    "PHOT",
    "TKT",
    "TOT",
    "CHADT",
    "LINT",
    "AZOST",
    "CVT",
    "EGT",
    "BRST",
    "FNT",
    "GST",
    "PMDT",
    "UYST",
    "NDT",
    "ADT",
    "AMST",
    "ART",
    "BRT",
    "CLST",
    "FKST",
    "FKST Falkland Islands Summer",
    "GFT",
    "PMST",
    "PYST",
    "ROTT",
    "SRT",
    "UYT",
    "NST",
    "NT",
    "AMT",
    "AST",
    "BOT",
    "CDT Cuba",
    "CLT",
    "COST",
    "ECT",
    "EDT",
    "FKT",
    "GYT",
    "PYT",
    "VET",
    "ACT Acre",
    "CDT",
    "COT",
    "CST Cuba",
    "EASST",
    "ECT Ecuador",
    "EST",
    "PET",
    "CST",
    "EAST",
    "GALT",
    "MDT",
    "MST",
    "PDT",
    "AKDT",
    "CIST",
    "PST",
    "AKST",
    "GAMT",
    "GIT",
    "HADT",
    "MART",
    "MIT",
    "CKT",
    "HAST",
    "HST",
    "TAHT",
    "NUT",
    "SST Samoa",
    "BIT",
]

@app.route('/')
def index():
    return render_template('index.html', timezones=timezones)

@app.route('/convert', methods=['POST'])
def convert():
    selected_timezone = request.form.get('timezone')
    selected_target_timezone = request.form.get('target_timezone')
    user_time_str = request.form.get('user_time')

    try:
        user_time = datetime.strptime(user_time_str, '%I:%M %p')
        user_time = pytz.timezone(selected_timezone).localize(user_time)
        converted_time = user_time.astimezone(pytz.timezone(selected_target_timezone))
        return render_template('index.html', timezones=timezones, user_time=user_time_str, converted_time=converted_time)
    except ValueError:
        error_message = "Invalid time format. Please use '7:00 PM' format."
        return render_template('index.html', timezones=timezones, error_message=error_message)

if __name__ == '__main__':
    app.run(debug=True)
